server:
  port: 8887

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: portfolio-service
              uri: lb://portfolio-service
              predicates:
                - Path=/portfolio/**
              filters:
                - StripPrefix=1

            - id: analytics-service 
              uri: lb://analytics-service 
              predicates: 
                - Path=/analytics/** 
              filters: 
                - StripPrefix=1
            
            - id: ai-service 
              uri: lb://ai-service
              predicates: 
                - Path=/ai/** 
              filters: 
                - StripPrefix=1

            - id: mcp-server
              uri: lb://mcp-server            
              predicates:
                - Path=/mcp/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,gateway
  endpoint:
    health:
      show-details: always

