server:
  port: 8883

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always