ADMIN_API_KEY: ${ADMIN_API_KEY}

server:
  port: 8889

spring:
  application:
    name: portfolio-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/portfolio
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always
