server:
  port: 8887

spring:
  application:
    name: portfolio-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/portfolio
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
